use_frameworks!

platform :ios, '9.0'

target 'PMLoadingProgress_Example' do
  pod 'PMLoadingProgress', :path => '../'

  target 'PMLoadingProgress_Tests' do
    inherit! :search_paths

    
  end
end
